// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASHYeA0M_jt2WQWxxjMflOx9yMO_j1JUE',
    appId: '1:518415891677:web:ec55e5fb0a051d08a16f34',
    messagingSenderId: '518415891677',
    projectId: 'teagarden-7a29d',
    authDomain: 'teagarden-7a29d.firebaseapp.com',
    storageBucket: 'teagarden-7a29d.firebasestorage.app',
    measurementId: 'G-Q24EQ2VS1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7HNHGrHAOGZg-2WSdAoEDIlr0lZ67pM',
    appId: '1:518415891677:android:43de67f1b1e85ebaa16f34',
    messagingSenderId: '518415891677',
    projectId: 'teagarden-7a29d',
    storageBucket: 'teagarden-7a29d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcISkO75N5C_rq6NDgmpUkFpmLq8y00eE',
    appId: '1:518415891677:ios:4a921c4dac0d6f9ea16f34',
    messagingSenderId: '518415891677',
    projectId: 'teagarden-7a29d',
    storageBucket: 'teagarden-7a29d.firebasestorage.app',
    iosClientId: '518415891677-bmm2ha5l7es6le5manlbjm850rfs89kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.teapulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcISkO75N5C_rq6NDgmpUkFpmLq8y00eE',
    appId: '1:518415891677:ios:4a921c4dac0d6f9ea16f34',
    messagingSenderId: '518415891677',
    projectId: 'teagarden-7a29d',
    storageBucket: 'teagarden-7a29d.firebasestorage.app',
    iosClientId: '518415891677-bmm2ha5l7es6le5manlbjm850rfs89kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.teapulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASHYeA0M_jt2WQWxxjMflOx9yMO_j1JUE',
    appId: '1:518415891677:web:8d147595bdf93063a16f34',
    messagingSenderId: '518415891677',
    projectId: 'teagarden-7a29d',
    authDomain: 'teagarden-7a29d.firebaseapp.com',
    storageBucket: 'teagarden-7a29d.firebasestorage.app',
    measurementId: 'G-BRTMZBWPB6',
  );
}
